### ISSUE TITLE
Make it clear to user which fields will be displayed publicly

### ISSUE THREAD

**Issue by hannahkane** [mozilla/clubs-events#7]
It seems that some of the data is going to be displayed publicly in the gallery, while other pieces are for staff eyes only. As a user, I'd want to understand who the audience is going to be for the data I'm entering.

**Comment by flukeout** [comment]
We added some copy to the top of the form to make this more clear. 

@xmatthewx Are there any fields we shouldn't show publicly? Maybe not the "Your Feedback" field? If so, we can indicate to the user that it will be shared privately.

I'm not actually sure if we can claim that though, because the spreadsheet we're using is readable by anyone.

**Comment by xmatthewx** [comment]
Agreed. We shouldn't promise privacy.
